### ISSUE TITLE
installing pdb2pqr from apbs-pdb2pqr 3.0?

### ISSUE THREAD

**Issue by jwhowarth** [Electrostatics/pdb2pqr#10]
The current apbs-pdb2pqr 3.0 release doesn't appear to perform any installations for pdb2pqr. Using...

$ mkdir build
$ cd build
$ cmake -DENABLE_PYTHON=ON -DCMAKE_C_FLAGS="-fPIC" ..
$ cmake --build .

however it is unclear how the 'built' pdb2pqr is supposed to be installed. Certainly executing...

PYTHONPATH=propka31 python3.8 -m pytest

fails with...

/opt/local/bin/python3.8: No module named pytest

despite apbs-3.0.0/pdb2pqr/README.md claiming that 'Testing can happen from this directory:'

**Comment by sobolevnrm** [comment]
Hello @jwhowarth -- please try installing APBS from one of our new releases.  It should work much better.  Thanks.

**Comment by intendo** [comment]
@jwhowarth, we recently split up APBS-PDB2PQR into separate repositories. 
For APBS, you can find the instructions at https://apbs.readthedocs.io/en/latest/getting/index.html. 
For PDB2PQR, https://pdb2pqr.readthedocs.io/en/latest/getting.html
