### ISSUE TITLE
GLYCAM on pdb2pqr?

### ISSUE THREAD

**Issue by shaharsu** [Electrostatics/pdb2pqr#111]
Hi all,

I'm interested in adding residues/atoms from glycam to pdb2pqr's AMBER.DAT and AMBER.names files, but am having a hard time finding any kind of instructions on how to do it. Does anyone know of a resource that can help me with that, or even better - a .DAT file with the atoms already included?

**Comment by sobolevnrm** [comment]
My apologies; the documentation is not very good.  The format of the DAT file is 
```
residue_name atom_name atom_charge atom_radius atom_type
```
although the `atom_type` field is not used. The parsing code is at https://github.com/Electrostatics/pdb2pqr/blob/c3508a203d518311e67cea60c3d28632621994d1/pdb2pqr/forcefield.py#L207

The `*.names` file actually is documented:  https://pdb2pqr.readthedocs.io/en/latest/formats/xml-names.html

I hope this helps.
