### ISSUE TITLE
pdb2pqr30 no nucleic acid residues

### ISSUE THREAD

**Issue by brjagger** [Electrostatics/pdb2pqr#120]
I am running pdb2pqr30 from the current github version of pdb2pqr 

    pdb2pqr30 4UN3.pdb test.pqr 

and receive the following error: 

    AttributeError: module 'pdb2pqr.aa' has no attribute 'RC'

I still receive this error if i first manually rename the RNA residues to from A to RA, etc.

I am attaching the error trace: [err.txt](https://github.com/Electrostatics/pdb2pqr/files/5320163/err.txt)
the pdb is PDB id 4UN3 taken directly from the web.

**Comment by sobolevnrm** [comment]
PR #122 will fix this issue but will still need #121 to be addressed for useful nucleic acid support.
