### ISSUE TITLE
How to generate standard format PDB files from pdb2pqr?

### ISSUE THREAD

**Issue by tdudgeon** [Electrostatics/pdb2pqr#126]
I'm wanting to generate standard PDB files from pdb2pqr so that I can utilise the optimised protonation of proteins in other tools that need standard PDB formats. By this I mean (at least):
- the 2 cols after the X, Y, Z coords have the values from the input PDB file, not the charge and radius
- the final col with the atom type and charge are present

Is this possible somehow?

**Comment by sobolevnrm** [comment]
It's not directly possible but we're working on features to make this feature.  I'll let you know when those are available.  Thank you!

**Comment by intendo** [comment]
Is this the same as #110?

**Comment by sobolevnrm** [comment]
Yes.
