### ISSUE TITLE
generatet PQR files from PROPKA results

### ISSUE THREAD

**Issue by haoasakura12** [Electrostatics/pdb2pqr#127]
Dear all, 

I'm new in pdb2pqr, so I'm sorry if this is not the place for asking...

I'm trying to use the pdb2pqr to correct missing atoms and add hydrogens in my PDB file. I have introduced the `--titration-state-method propka --with-ph 4.0, it gives me only the PROPKA results, but does not change the PQR file (neutralizing the side chain of amino-acids with calculated pKa = 6.0). 

The entire command line that I'm using is:
`pdb2pqr30 --keep-chain --ligand ~/Downloads/Molecule.mol2 --titration-state-method propka --with-ph 5.0 -o 5.0 --ff=AMBER 1mqi ~/Documentos/1mq2`

Is there a way to PQR file be changed according the results of PROPKA calculation, like in the web server?
Thanks for your help

**Comment by sobolevnrm** [comment]
Could you please share the input and output files; either here or via email:  nathanandrewbaker@gmail.com ?

**Comment by haoasakura12** [comment]
Hy sobolvnrm,

Thanks for your help. These are the files:
[files.zip](https://github.com/Electrostatics/pdb2pqr/files/5506863/files.zip)

**Comment by haoasakura12** [comment]
Dear all,

I also want to know if it is possible to include carbohydrate structures together with the ligand to generate prq file.

Thanks for your time and help

**Comment by sobolevnrm** [comment]
> Dear all,
> 
> I also want to know if it is possible to include carbohydrate structures together with the ligand to generate prq file.
> 
> Thanks for your time and help

It is not currently possible to use carbohydrate structures and a ligand (essentially multiple ligands).

**Comment by sobolevnrm** [comment]
> --keep-chain --ligand ~/Downloads/Molecule.mol2 --titration-state-method propka --with-ph 5.0 -o 5.0 --ff=AMBER 1mqi ~/Documentos/1mq2

When I run this, it doesn't generate a PQR file at all due to a problem assigning charges to the ligand.  The [1MQI](https://www.rcsb.org/structure/1MQI) PDB entry includes a ligand with a fluorine atom.  However, the MOL2 file you sent me contained a bromine.  Did you modify the MOL2 file but not the PDB?

**Comment by haoasakura12** [comment]
Sorry, i sent you the wrong input. The real one is 1mqh instead 1mqi.
Again, thank you for your help

Enviado do Yahoo Mail no Android 
 
  Em sáb, 14 14e nov 14e 2020 às 21:25, Nathan Baker<notifications@github.com> escreveu:   



--keep-chain --ligand ~/Downloads/Molecule.mol2 --titration-state-method propka --with-ph 5.0 -o 5.0 --ff=AMBER 1mqi ~/Documentos/1mq2


When I run this, it doesn't generate a PQR file at all due to a problem assigning charges to the ligand. The 1MQI PDB entry includes a ligand with a fluorine atom. However, the MOL2 file you sent me contained a bromine. Did you modify the MOL2 file but not the PDB?

**Comment by sobolevnrm** [comment]
I am able to reproduce this bug but have not figured out what is causing it.

**Comment by sobolevnrm** [comment]
Looking at the log file produced by PDB2PQR, there are several warnings of the form:
```
WARNING:pdb2pqr.biomolecule:PDB2PQR could not identify the following residues and residue numbers as returned by PROPKA or PDB2PKA
WARNING:pdb2pqr.biomolecule:             N+    3 A
WARNING:pdb2pqr.biomolecule:             LYS   4 A
WARNING:pdb2pqr.biomolecule:             GLU  13 A
WARNING:pdb2pqr.biomolecule:             TYR  16 A
```
This is likely the source of the problem.  I'm not sure why PDB2PQR didn't recognize these.

**Comment by sobolevnrm** [comment]
This is due to incorrect key formatting in `apply_pka_values` (https://github.com/Electrostatics/pdb2pqr/blob/8f8cde8b5589b450cf404782976a2c3cc6edc471/pdb2pqr/biomolecule.py#L754).  I'm working on a fix.

**Comment by haoasakura12** [comment]
Dear,

I would like to thank you. 
I read you found the incorrect formatting and are now fixing it. When it is fixed, what should I do?
Is there a way to import the solution to my computer and try it?

**Comment by sobolevnrm** [comment]
If you're feeling brave/impatient, you can do the following from a clean virtual environment:

1. `git clone https://github.com/Electrostatics/pdb2pqr.git`
2. `pip install -e .`

Otherwise, I'd look for a new PDB2PQR release in the next few days (perhaps tonight if I can get things squared away in time).

**Comment by sobolevnrm** [comment]
Err... might take me longer than a day or so to generate a new release.  I forgot that we are missing some things in the new Python implementation.  I'd use the approach above for now.

**Comment by haoasakura12** [comment]
Ok.
Again, thanks for your help.

**Comment by haoasakura12** [comment]
Dear, 

Is there a way to know when this new version will be released for pip upgrade?

**Comment by sobolevnrm** [comment]
Hi --

This is a nights/weekends undertaking for me due to other constraints so I don't have a specific timeline.  You can track progress at https://github.com/Electrostatics/pdb2pqr/issues/129.  In the meantime, you might want to try the approach I outlined above:
```
git clone https://github.com/Electrostatics/pdb2pqr.git
pip install -e .
```

Thanks
