### ISSUE TITLE
Fix cif import

### ISSUE THREAD

**Issue by speleo3** [Electrostatics/pdb2pqr#130]
The `mmcif_pdbx` API was changed in a backwards-incompatible way in https://github.com/Electrostatics/mmcif_pdbx/commit/9f12cce52a0b3352510c2285aff3f560fc4958d7

https://github.com/Electrostatics/pdb2pqr/blob/master/pdb2pqr/cif.py still uses the old API.

**Comment by sobolevnrm** [comment]
I can reproduce this problem on the master branch with `pdb2pqr30 --ff=AMBER --ffout=AMBER --titration-state-method=propka --with-ph=7.5 1fas.cif 1fas.pqr`

**Comment by sobolevnrm** [comment]
However, I haven't figured out how to fix this problem yet.  @speleo3 -- any hints?

**Comment by sobolevnrm** [comment]
> However, I haven't figured out how to fix this problem yet. @speleo3 -- any hints?

Never mind; I figured it out.  Thanks!
