### ISSUE TITLE
Adding hydroxyproline to AMBER.DAT

### ISSUE THREAD

**Issue by jcminerlanl** [Electrostatics/pdb2pqr#145]
I am trying to incorporate hydroxyproline (HYP) parameters from "A new set of molecular mechanics parameters for hydroxyproline and its use in molecular dynamics simulations of collagen‐like peptides" (https://onlinelibrary.wiley.com/doi/full/10.1002/jcc.20301).

The following are the parameters I placed in pdb2pqr/dat/AMBER.DAT
[outmod.log](https://github.com/Electrostatics/pdb2pqr/files/5638191/outmod.log)

HYP     N       -0.254800       1.8240  N
HYP     CD      0.059500        1.9080  CT
HYP     HD1     0.070000        1.3870  H1
HYP     HD2     0.070000        1.3870  H1
HYP     CG      0.040000        1.9080  CT
HYP     HG      0.041600        1.4870  HC
HYP     OD      -0.613400       1.7210  OH
HYP     HO1     0.385100        0.0000  HO
HYP     CB      0.020300        1.9080  CT
HYP     HB1     0.042600        1.4870  HC
HYP     HB2     0.042600        1.4870  HC
HYP     CA      0.004700        1.9080  CT
HYP     HA      0.077000        1.3870  H1
HYP     C       0.589600        1.9080  C

Here is what the HYP residue looks like in the original pdb before running pdb2pqr:

ATOM     39  N   HYP A   3      -1.407 -12.613 -10.054  1.00  0.00           N
ATOM     40  CA  HYP A   3      -0.817 -11.288  -9.952  1.00  0.00           C
ATOM     41  C   HYP A   3      -1.178 -10.537  -8.668  1.00  0.00           C
ATOM     42  O   HYP A   3      -2.335 -10.570  -8.239  1.00  0.00           O
ATOM     43  CB  HYP A   3      -1.301 -10.537 -11.194  1.00  0.00           C
ATOM     44  CG  HYP A   3      -2.495 -11.368 -11.642  1.00  0.00           C
ATOM     45  OD  HYP A   3      -2.067 -12.647 -12.103  1.00  0.00           O
ATOM     46  CD  HYP A   3      -3.250 -11.536 -10.330  1.00  0.00           C
ATOM     47  HA  HYP A   3       0.262 -11.390 -10.010  1.00  0.00           H
ATOM     48 HB1  HYP A   3      -1.661  -9.549 -10.909  1.00  0.00           H
ATOM     49 HB2  HYP A   3      -0.535 -10.450 -11.961  1.00  0.00           H
ATOM     50  HG  HYP A   3      -3.086 -10.866 -12.409  1.00  0.00           H
ATOM     51 HO1  HYP A   3      -1.947 -12.619 -13.068  1.00  0.00           H
ATOM     52 HD1  HYP A   3      -4.243 -11.929 -10.534  1.00  0.00           H
ATOM     53 HD2  HYP A   3      -3.318 -10.567  -9.836  1.00  0.00           H

When I attempt to run the following command:
$ pdb2pqr30 --ff=AMBER test-mod.pdb outmod.pdb

I get an outmod.pdb and outmod.log file (attached) and the HYP residue is missing.

Can someone help me understand why I cannot get HYP parameters into AMBER for pdb2pqr processing?

**Comment by sobolevnrm** [comment]
Can you please share your *DAT and *PDB files so we can investigate?  Thank you.

________________________________

**Comment by jcminerlanl** [comment]
I resolved it. I think the parameters I was using lacked an 'O'.
Once all of the atoms were in, and named to match the PDB, the conversion worked fine.
Thank you.
