### ISSUE TITLE
--pdb-output mislabel H as N

### ISSUE THREAD

**Issue by bhwl12** [Electrostatics/pdb2pqr#147]
I use the following command to prepare 6LZM, pdb2pqr mislabeled H as N in the pdb file. The output file was attached.

pdb2pqr30 6lzm.pdb test --ff CHARMM --pdb-output 6lzm_prep.dpb

[6lzm_prep.dpb.txt](https://github.com/Electrostatics/pdb2pqr/files/5670010/6lzm_prep.dpb.txt)

Thanks!

**Comment by sobolevnrm** [comment]
Thank you for all of the supporting information.  We will look into this as soon as possible.
