### ISSUE TITLE
How can I locate the `extensions` package?

### ISSUE THREAD

**Issue by aanastasiou** [Electrostatics/pdb2pqr#149]
Hello

Is it possible to clarify the differences between release 2.1.1 and 3.0.0 please?

[2.1.1 seems to include](https://packages.debian.org/sid/amd64/pdb2pqr/filelist) an `extensions` package which enables options for generating hydrogen bonds, contacts map and salt bridges.

`extensions` is not there in 3.0.0 and there are also some differences in terms of options (`--ph-calc-method`` is now `--titration-state-method` (?) and there is also a separate `--pH` option? )

Are `extensions` provided separately? I hope I have not missed something too obvious in the docs :)

**Comment by sobolevnrm** [comment]
Hello --

I need to create a useful change log for PDB2PQR.

We have removed the extensions option while refactoring the code.  Can you please share more about your use case for the extensions so we can determine how best to support it?

Thank you

**Comment by aanastasiou** [comment]
Hello @sobolevnrm 

The extensions I was interested in were the `hbonds` and `contact` that included options for generating very detailed hydrogen bond and contact map outputs. Presumably that was in addition to useful operations such as pH determination and atom "debumping". It is the combination of these two capabilities that appeal to me.

Sounds like capabilities that are not coming back (?).

**Comment by sobolevnrm** [comment]
Hi @aanastasiou --

I'll create an issue to restore the functionality but I can't predict how long it will take to implement.

Thanks,

Nathan

**Comment by aanastasiou** [comment]
Hello @sobolevnrm and thank you for your response. I suppose that the code would require modification which means a more intimate knowledge of details than an outsider would have. But in any case, if there is anything I could help with, please let me know. 

All the best
