### ISSUE TITLE
Reporting bug running pdb2pqr30 from the command line 

### ISSUE THREAD

**Issue by shaoqx** [Electrostatics/pdb2pqr#150]
I installed the program from `pip install pdb2pqr`.
The error was like this when I call `pdb2pqr30 --help` from the command line:
```
Traceback (most recent call last):
  File "path/pdb2pqr30", line 9, in <module>
    sys.exit(main())
TypeError: main() missing 1 required positional argument: 'args'
```
I looked into the pdb2pqr30 file and found the script is different from \_\_main\_\_.py in the package:
```
import re
import sys
from pdb2pqr.main import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```
It seems outdated?  

BTW, `python -m pdb2pqr` works well.

**Comment by shaoqx** [comment]
Another problem:
when I ran this ` python -m pdb2pqr test.pdb test.pqr` with a pdb without ligands.
I receive this error: 
```
...
  File "path/pdb2pqr/main.py", line 502, in non_trivial
    matched_atoms = hitlist + lig_atoms
UnboundLocalError: local variable 'lig_atoms' referenced before assignment
```
I looked into the code and found the **lig_atoms** and **missing_atoms** are only assigned if args.ligand is not None. But it is used for no-ligand case also. 
I added a `lig_atoms = []` and `missing_atoms = []` at the beginning of the `non_trivial()` function and solved the problem. I wonder if this change is valid? Will it affect any other functions?

**Comment by sobolevnrm** [comment]
Hello --

We are fixing issues with the pip version of the package.  I cannot reproduce this error with the master branch, so please try the following from a clean virtual environment:

```
git clone https://github.com/Electrostatics/pdb2pqr.git
cd pdb2pqr
pip install .
```

Thank you
