### ISSUE TITLE
How can I protonate with ion centers.

### ISSUE THREAD

**Issue by shaoqx** [Electrostatics/pdb2pqr#151]
Hi,
I'm dealing with a PDB structure that contains 2 Zn2+ centers. The resulting structure form PDB2PQR do not contain these Zn and the coordinating HIS is protonated like the Zn does not exist. Can I fix this by some settings in the program? (like setting the Zn as a ligand?)
Would you mind give me some suggestions?

**Comment by shaoqx** [comment]
Also, how can I deal with structure with multiple chains?

**Comment by sobolevnrm** [comment]
> Hi,
> I'm dealing with a PDB structure that contains 2 Zn2+ centers. The resulting structure form PDB2PQR do not contain these Zn and the coordinating HIS is protonated like the Zn does not exist. Can I fix this by some settings in the program? (like setting the Zn as a ligand?)
> Would you mind give me some suggestions?

Unfortunately, PDB2PQR does not currently support metal centers.  These will be removed by the program and you will have to reinstatement (possibly changing the titration states of the ligating groups) after running the structure through PDB2PQR.

**Comment by sobolevnrm** [comment]
> Also, how can I deal with structure with multiple chains?

PDB2PQR already handles multiple chains.

**Comment by shaoqx** [comment]
Thank you for your kind reply! I guess it was that PyMol does not recognize that all chains start from index 1 misleading me. The function was all good!

**Comment by sobolevnrm** [comment]
Great; thank you for the follow-up!
