### ISSUE TITLE
Pytest fails in vanilla conda environment

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/pdb2pqr#156]
Missing module `testfixtures`.

**Comment by sobolevnrm** [comment]
Adding `testfixtures` to the `setup.py` `test_requires` list does not fix this problem.  In fact, when running `python setup.py test` to test, I get the message:
```
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
```

Maybe it's time to upgrade to `tox`.  @intendo what do you think?

**Comment by sobolevnrm** [comment]
Actually, let's not upgrade to tox--it does not play nicely with conda.

**Comment by intendo** [comment]
@sobolevnrm it looks like there is a tox conda plugin that you can use to integrate tox and conda.
See https://github.com/tox-dev/tox-conda

**Comment by sobolevnrm** [comment]
> @sobolevnrm it looks like there is a tox conda plugin that you can use to integrate tox and conda.
> See https://github.com/tox-dev/tox-conda

Thank you but it seems like a lot of gymnastics to enable testing.
