### ISSUE TITLE
Similarity "metrics" references (?)

### ISSUE THREAD

**Issue by aanastasiou** [Electrostatics/pdb2pqr#174]
Would it be possible to provide one or two references to the similarity metrics that are calculated by the `similarity` tool please?
And specifically, what do "Hodkgin" and "Carbo" refer to?

For some reason, the `analysis` and `similiarity` are somewhat unstable. For example `similarity` might crash (core dump) for a pair of scalars A,B but not if invoked with B,A. 

`analysis` might also crash for some files but not others. I am going to look into this in more detail at some point, specifically to see if there is anything in the `.dx` files that causes the crashes and whether it might be something as simple as defining a mask to avoid those numeric values. However, I don't think that a numerical problem would cause something as severe as core dump without any sort of message.

**Comment by sobolevnrm** [comment]
Here is a reference for the metrics:

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2561295/

I am working to replace the unstable C code with more stable Python code but progress is slow.

Thank you

**Comment by aanastasiou** [comment]
Many thanks.
