### ISSUE TITLE
UnboundLocalError: local variable 'pH_opt' referenced before assignment

### ISSUE THREAD

**Issue by cgseitz** [Electrostatics/pdb2pqr#176]
Hello,

I am running into an error trying to use APBS. My pdb is quite large (300k atoms); when I uploaded it to the web server, it quickly said that my system was too large to use. I then tried using the command line version ```pdb2pqr/2018.2.1``` using the command ```pdb2pqr.py --ff=charmm --ffout=charmm --with-ph=7.5 --ph-calc-method=propka --verbose --summary 48chains_for_MD.pdb test3.pqr```. This runs for maybe an hour and then results in an error:
```	
        CYS B 217 is a free cysteine
	CYS A 217 is a free cysteine
	CYS E 557 is a free cysteine
Done.
Checking if we must debump any residues... 
Done.
Running PROPKA and applying at pH 7.50... 
Traceback (most recent call last):
  File "/software/repo/moleculardynamics/pdb2pqr/2018.2.1/pdb2pqr.py", line 62, in <module>
    mainCommand(sys.argv)
  File "main.py", line 740, in mainCommand
  File "main.py", line 339, in runPDB2PQR
  File "src/routines.py", line 1596, in runPROPKA
  File "propka30/Source/protein.py", line 581, in writePKA
  File "propka30/Source/output.py", line 174, in writePKA
  File "propka30/Source/output.py", line 283, in getFoldingProfileSection
  File "propka30/Source/protein.py", line 629, in getPHopt
UnboundLocalError: local variable 'pH_opt' referenced before assignment
```
I found this happens both with the charmm and amber force fields, but I am quite unsure how to fix it. I was using a linux system when I got this error. Thanks for your help!

Best,
Christian

**Comment by cgseitz** [comment]
Robert Konecny was able to fix the issue - it just required using a newer version of pdb2pqr.  His steps to run the newer pdb2pqr are reproduced here:

```
conda create --name pdb2pqr pip
conda activate pdb2pqr
pip install requests pdb2pqr
(pdb2pqr) $ pdb2pqr30 --version
pdb2pqr30 3.4.0
conda deactivate
```
and for future users, the run command I needed was 
```
pdb2pqr30 --ff AMBER --pdb-output 48chains_charmm.pdb --titration-state-method propka --with-ph 7.5 48chains_for_MD.pdb 48chains_charmm.pqr
```

**Comment by sobolevnrm** [comment]
Great!

________________________________
