### ISSUE TITLE
Charge of C-terminus in pdb2pqr

### ISSUE THREAD

**Issue by anna875x** [Electrostatics/pdb2pqr#177]
This may be a very simple question (sorry), but I'm unfamiliar with changing settings in pdb2pqr and have only ever used the default parameters.

I would like to use PyMOL ABPS to do an electrostatic calculation. All parameters will be the default, except I wish to change the C-terminal charge from negative to neutral. According to the documentation, there is a way to do this: https://pdb2pqr.readthedocs.io/en/master/_modules/pdb2pqr/main.html (I ctrl+F searched to find this setting in the script). Where/how can I make this adjustment? If possible, I want to keep using the APBS PyMOL plugin.

**Comment by speleo3** [comment]
Command line options `--ff=PARSE --neutralc` should do the trick, the PyMOL APBS panel "Advanced Configuration" tab has a field for that:

![pymol-apbs-neutralc-2](https://user-images.githubusercontent.com/1239490/107616062-969bb300-6c4d-11eb-8354-daaeb24b6e4d.png)

**Comment by anna875x** [comment]
You are a LIFESAVER!! I didn't realize it was so easy, thank you so much!
