### ISSUE TITLE
Ligand parameterization not working for me. 

### ISSUE THREAD

**Issue by vpurohit15** [Electrostatics/pdb2pqr#178]
Hello,

I have been recently trying to use PDB2PQR to generate .pqr files for my ligand. I generated .mol2 files for it after adding charges and hydrogens for it on chimera and then deleting the rest of the protein and additional ligands before saving the ligand .mol2 file. However, while using pdb2pqr to generate the .pqr file in an AMBER force field, I get the following error for the ligand: "PDB2PQR could not successfully parameterize the desired ligand; it has been left out of the PQR file."
Looking for pointers on what I could be doing wrong here. I've attached all the files (as .txt - designation in the name) associated with this PDB2PQR run in this email. Any insight would be greatly appreciated!

[ligand_pdb2pqr_mol2.txt](https://github.com/Electrostatics/pdb2pqr/files/5998937/ligand_pdb2pqr_mol2.txt)
[protein_pdb2pqr_pdb.txt](https://github.com/Electrostatics/pdb2pqr/files/5998942/protein_pdb2pqr_pdb.txt)
[pdb2pqr_stderr.txt](https://github.com/Electrostatics/pdb2pqr/files/5998943/pdb2pqr_stderr.txt)
[pdb2pqr_stdout.txt](https://github.com/Electrostatics/pdb2pqr/files/5998944/pdb2pqr_stdout.txt)
[ligand-input_json.txt](https://github.com/Electrostatics/pdb2pqr/files/5998956/ligand-input_json.txt)
[ligandpdb2pqr_in.txt](https://github.com/Electrostatics/pdb2pqr/files/5998965/ligandpdb2pqr_in.txt)
[ligandpdb2pqr-input_p.txt](https://github.com/Electrostatics/pdb2pqr/files/5998968/ligandpdb2pqr-input_p.txt)
[generated_pqrfile.txt](https://github.com/Electrostatics/pdb2pqr/files/5998974/generated_pqrfile.txt)
[generated_propkafile.txt](https://github.com/Electrostatics/pdb2pqr/files/5998984/generated_propkafile.txt)

**Comment by sobolevnrm** [comment]
Can you please let us know what version of PDB2PQR you are using and the command line arguments with which you invoked the program?  Thanks.

**Comment by sobolevnrm** [comment]
The latest version of PDB2PQR (2a7a740) gave the following error with these input files:
```
Traceback (most recent call last):
  File "C:\Users\bake113\Anaconda3\envs\pdb2pqr\Scripts\pdb2pqr30-script.py", line 33, in <module>
    sys.exit(load_entry_point('pdb2pqr', 'console_scripts', 'pdb2pqr30')())
  File "c:\users\bake113\onedrive - pnnl\documents\git\pdb2pqr\pdb2pqr\main.py", line 820, in main
    if main_driver(args) == 1:
  File "c:\users\bake113\onedrive - pnnl\documents\git\pdb2pqr\pdb2pqr\main.py", line 762, in main_driver
    biomolecule, definition, ligand = setup_molecule(
  File "c:\users\bake113\onedrive - pnnl\documents\git\pdb2pqr\pdb2pqr\main.py", line 404, in setup_molecule
    ligand.read(ligand_file)
  File "c:\users\bake113\onedrive - pnnl\documents\git\pdb2pqr\pdb2pqr\ligand\mol2.py", line 458, in read
    mol2_file = self.parse_bonds(mol2_file)
  File "c:\users\bake113\onedrive - pnnl\documents\git\pdb2pqr\pdb2pqr\ligand\mol2.py", line 554, in parse_bonds
    raise ValueError(err)
ValueError: Unknown bond type: am
```
However, the `am` (amide) bond is a legitimate bond type in MOL2 (see http://chemyang.ccnu.edu.cn/ccb/server/AIMMS/mol2.pdf). Therefore, something in PDB2PQR is either undocumented or broken.

**Comment by sobolevnrm** [comment]
Unfortunately, the `am` bond does not look like something we will be able to support in the near future.  However, we will improve the PDB2PQR output to make this gap clearer to users.
