### ISSUE TITLE
Adding 2 ligands simultaneously

### ISSUE THREAD

**Issue by brcnacar** [Electrostatics/pdb2pqr#187]
I would like to introduce 2 mol2 files: one for phosphotyrosine and one for ATP. But I am only allowed to submit one mol2 file. how can I do this?

**Comment by sobolevnrm** [comment]
I think you can include multiple molecules in a single mol2 file; however, you may need to edit it manually.  This feature isn't currently planned for support in PDB2PQR. 

Thank you
