### ISSUE TITLE
CRITICAL:Unable to recognize user-defined forcefield file cnh.prmtop! Please use a valid parameter file.

### ISSUE THREAD

**Issue by Eduardo1ra** [Electrostatics/pdb2pqr#190]
Hi!

I have been trying to generate a pqr file for my system (a modified carbon nanotube) that was parameterized in the Amber software. I have a **formatted pdb file** CNHox_pqr.pdb, **Amber topology file** cnh.prmtop. I use the following command line:

 pdb2pqr30 CNHox_pqr.pdb CNHox_pqr.pqr --userff cnh.prmtop --assign-only --apbs-input input_ABDS.in --usernames cnh.prmtop
INFO:PDB2PQR v3.1.0: biomolecular structure conversion software.
INFO:Please cite:  Jurrus E, et al.  Improvements to the APBS biomolecular solvation software suite.  Protein Sci 27 112-128 (2018).
INFO:Please cite:  Dolinsky TJ, et al.  PDB2PQR: expanding and upgrading automated preparation of biomolecular structures for molecular simulations. Nucleic Acids Res 35 W522-W525 (2007).
INFO:Checking and transforming input arguments.
INFO:Loading topology files.
INFO:Loading molecule: CNHox_pqr.pdb
INFO:Setting up molecule.
INFO:Created biomolecule object with 1 residues and 229 atoms.
INFO:Setting termini states for biomolecule chains.
INFO:Loading forcefield.
CRITICAL:Unable to recognize user-defined forcefield file cnh.prmtop! Please use a valid parameter file.
CRITICAL:Giving up.

I also tried to use the flag --ff=AMBER, but it didn't work. I also have a mol2 file (formatted for Amber) that has the atomic charges, but I don't know how to use it in PDB2PQR. Could anyone help me with this error?

![Screenshot from 2021-05-13 16-18-14](https://user-images.githubusercontent.com/76981769/118175748-e33a8a00-b406-11eb-8536-8fb65000cbb6.png)

My pdb file (in txt format):

[CNHox_pqr.txt](https://github.com/Electrostatics/pdb2pqr/files/6474672/CNHox_pqr.txt)

**Comment by intendo** [comment]
The primary error looks like pdb2pqr cannot read your cnh.prmtop file.

I tried to run the CNHox_pqr.pdb file on the [APBS/PDB2PQR web server](https://server.poissonboltzmann.org) (which still runs version 2.1.0 of pdb2pqr) and got the following output in stderr:
```
--------------------------
PDB2PQR - a Python-based structural conversion utility
--------------------------
Please cite your use of PDB2PQR as:
  Dolinsky TJ, Nielsen JE, McCammon JA, Baker NA.
  PDB2PQR: an automated pipeline for the setup, execution,
  and analysis of Poisson-Boltzmann electrostatics calculations.
  Nucleic Acids Research 32 W665-W667 (2004).

Beginning PDB2PQR...

Parsed Amino Acid definition file.
Created protein object -
	Number of residues in protein: 1
	Number of atoms in protein   : 229
Setting the termini... 
Done.
Checking for missing heavy atoms... 
DEBUG INFO: PDBInputError src/routines.py: 622 
Error encountered: No heavy atoms found. You may also see this message if PDB2PQR does not have parameters for any residue in your protein.
```

This indicates that the actual pdb file does not work with the default parameters. You may want try the web server to see if you can upload your files there and see if it works.

**Comment by sobolevnrm** [comment]
PDB2PQR requires a specific type of parameter file format:  https://pdb2pqr.readthedocs.io/en/latest/extending.html

Based on the naming convention you provided above, I suspect you are using standard AMBER parameter/topology formats.  PDB2PQR does not work with those.

**Comment by Eduardo1ra** [comment]
Hi Darren Curtis and Nathan Baker!
Thank you for your responses. I was using a standard AMBER parameter file as mentioned by Nathan. I'll follow the instructions for preparing this specific type of parameter file format.

**Comment by sobolevnrm** [comment]
Great; thank you!
