### ISSUE TITLE
DX file doesn't get written until the end

### ISSUE THREAD

**Issue by bb2n18** [Electrostatics/pdb2pqr#199]
Dear all,

I am very confused about the web server, because I am trying to use APBS on a protein, and I managed to make it work completely twice, but could never rerun the same calculation successfully then...
What happens is that the PDB2PQR module works well, then when I use that output as input in APBS, it runs and shows a successful ending with the green tick, but the output file is not written (O KB), and the DX file is incomplete (the last line if the file stopped being written right in the middle of it).
I don't understand why that would work once and not anymore then. Is there something I should know about using the web server? Depending on RAM or the web browser? ...
Here are attached the files.

Many thanks for your help,
Bastien

[2j01ai3g7v.pqr.txt](https://github.com/Electrostatics/pdb2pqr/files/6654854/2j01ai3g7v.pqr.txt)
[io.mc.txt](https://github.com/Electrostatics/pdb2pqr/files/6654836/io.mc.txt)

**Comment by bb2n18** [comment]
The dx file looks like:

# Data from 3.0
#
# POTENTIAL (kT/e)
#
object 1 class gridpositions counts 161 193 193
origin 3.504900e+01 2.942400e+01 1.843200e+01
delta 4.818750e-01 0.000000e+00 0.000000e+00
delta 0.000000e+00 4.638542e-01 0.000000e+00
delta 0.000000e+00 0.000000e+00 5.152604e-01
object 2 class gridconnections counts 161 193 193
object 3 class array type double rank 0 items 5997089 data follows
-1.684677e+00 -1.689424e+00 -1.694067e+00
-1.698635e+00 -1.703128e+00 -1.707527e+00
.....................
..........
-2.241366e+00 -2.232729e+00 -2.224007e+00
-2.215205e+00 -2.206323e+00


So it didn't print till the end...

**Comment by sobolevnrm** [comment]
@Eo300 @intendo can you please look into this?  This seems similar to an error that another user emailed me about.

Thank you

**Comment by Eo300** [comment]
Hi @bb2n18 , this was indeed a RAM-related issue, specifically with the web deployment.  Electrostatics/apbs-aws#120 has addressed the issue, and the change should be live now on the website.  Can you attempt another APBS calculation to confirm whether it is fixed on your end as well? Thanks!

**Comment by bb2n18** [comment]
Hi @Eo300, thank you very much for your reply and help. I have run a couple of new calculations and they both worked with complete dx files in output!
Many thanks!
