### ISSUE TITLE
pdb2pqr server issue

### ISSUE THREAD

**Issue by JungUn-Park** [Electrostatics/pdb2pqr#201]
Hello all,

I am trying to run a pdb2pqr and apbs using the web server, but all of my attempts are failing. Uploading my local pdb file gives me "~.pdb file upload failed" error, and running with a published pdb code also doesn't proceed at this step. Could you take a look, please? Thank you!

Best,
JungUn

**Comment by Eo300** [comment]
Does this error occur as soon as you select your file? If so, then your browser may be loading an older/cached version of the website, though doing a hard reload (Ctrl+Shift+R for Windows/Cmd+Shift+R for Mac) may resolve some issues.

**Comment by sobolevnrm** [comment]
Hello.  We will need an example PQR file to troubleshoot this issue.  Thank you.

**Comment by JungUn-Park** [comment]
Thank you for the quick response! Hard reload made it work! Thank you so much!
