### ISSUE TITLE
Run a ligand only

### ISSUE THREAD

**Issue by bb2n18** [Electrostatics/pdb2pqr#203]
Dear APBS team,

Is there a way to run APBS on a ligand only on the web server? Such as a lipid alone, a small molecule or even an atomic cation for example?

Thank you for your reply,
Best regards,
Bastien Belzunces

**Comment by sobolevnrm** [comment]
Hello --

This is not currently a feature but definitely something we can consider for the future.

Thank you

**Comment by sobolevnrm** [comment]
I'm sorry but we are unlikely to implement this feature.  There are too many other priorities currently competing for our developers' time.
