### ISSUE TITLE
PDB2PQR cannot parse the 7d1t.pdb file locally or when downloaded from RCSB.org

### ISSUE THREAD

**Issue by intendo** [Electrostatics/pdb2pqr#204]
Problem: 
- PDB2PQR cannot parse the 7d1t.pdb file locally or when downloaded from RCSB.org.

Steps to recreate the problem:
- Download file, [7d1t.pdb](https://files.rcsb.org/download/7d1t.pdburl), to you local filesystem
- Open the 7d1t.pdb file in your favorite editor (e.g. VS Code)
- Go to line 1936, and see the record, `CRYST1    1.000    1.000    1.000  90.00  90.00  90.00 P 1`
- Observe that the `1` at the end of the line is in column 58.
- According to the parser for CRYST1 records in the pdb.py source code, you can see the line that is looking for that `1` in columns 66-70. You can see this in the code, `self.z = int(line[66:70].strip())`, that correctly follows the PDB version 3.3 file format for [CRYST1](https://www.wwpdb.org/documentation/file-format-content/format33/sect8.html#CRYST1). According to the documentation, it is hard to determine for this example if the `P 1` is part of the space_group and missing a few values or if `P` is the space_group and `1` is supposed to be the Z value. The example from the PDB documentation shows the following:
```
         1         2         3         4         5         6         7         8
12345678901234567890123456789012345678901234567890123456789012345678901234567890
CRYST1   52.000   58.600   61.900  90.00  90.00  90.00 P 21 21 21    8 
CRYST1   42.544   69.085   50.950  90.00  95.55  90.00 P 1 21 1      2
Example of experimental method other than X-ray crystallography or fiber diffraction
CRYST1    1.000    1.000    1.000  90.00  90.00  90.00 P 1           1
```
- We observed the problem in both versions of PDB2PQR:
-- PDB2PQR [Version 3.0](https://github.com/Electrostatics/apbs-pdb2pqr/blob/b3bfeecbf4cfd04bf53f983e1a8064ef250bf25f/pdb2pqr/src/pdb.py#L1020)
-- PDB2PQR [Version 3.1](https://github.com/Electrostatics/pdb2pqr/blob/92ee6cf4b629dfa2e422c95ddad869f8a587d579/pdb2pqr/pdb.py#L937)

Options:
- [ ] Report the finding to RCSB.org
- Modify the code to handle this error:
- - [ ] Wrap the assignments with try/except and exit with an error
- - [ ] Assume that `P` is the space_group and assume the `1` is the Z value, and issue a warning
- - [ ] Assume that `P 1` is the space_group and that `` is the Z value and assign it to zero `0`, and issue a warning
- - [ ] Other?

**Comment by sobolevnrm** [comment]
This is no longer a problem as of commit 454fec9 (or earlier).
