### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by stefdoerr** [Electrostatics/pdb2pqr#211]
Hi, I just wanted to ask if the are plans for making a new pdb2pqr release for conda, because a project of mine depends on the package.
Thanks!

**Comment by sobolevnrm** [comment]
Hello.  I prefer pip as a distribution mechanism and, frankly, can't figure out conda forge to save my life. @tsenapathi do you have time to look at this?  Thanks!

**Comment by tsenapathi** [comment]
@sobolevnrm and @stefdoerr pdb2pqr is in the cond forge already ([](https://anaconda.org/conda-forge/pdb2pqr)) and is we have the latest release (3.1.0) here

**Comment by stefdoerr** [comment]
Right, I was just curious if you were planning a 3.1.1 version with the latest fixes

**Comment by tsenapathi** [comment]
Conda release is the same as the version in pypi. Currently, it is in 3.1.0. @sobolevnrm needs to decide on releasing of 3.1.1 version to pypi.

**Comment by sobolevnrm** [comment]
Ah -- got it.  I will try to get going on this over the next few days.  Thanks.

**Comment by stefdoerr** [comment]
Great, I see there is a new version now :) I'll close the issue

**Comment by stefdoerr** [comment]
Hi, sorry to bother about this. Do you have an ETA for the next release of PDB2PQR on conda-forge? I'd like to use the latest fixes like the RA->RU residue for my RNAs and the protonation disabling.
Thanks!

**Comment by sobolevnrm** [comment]
I can try to do that later this week or weekend, if @intendo agrees.  @tsenapathi can you help again with the conda version after I push the release?  Thanks, all.

**Comment by sobolevnrm** [comment]
- [ ] Update releases file with changes
- [ ] Delete old change log
- [ ] Update version number
- [ ] Run tests

**Comment by sobolevnrm** [comment]
The GitHub/PyPI part of this is done.  @tsenapathi are you able to generate the conda release?

**Comment by sobolevnrm** [comment]
@Eo300 and @intendo -- can we get 3.3.1 integrated into the webserver?  Thanks.

**Comment by tsenapathi** [comment]
Conda release is done!

**Comment by intendo** [comment]
Thank you for the Conda release? Do you happen to have the process documented?

**Comment by tsenapathi** [comment]
This process is automated, whenever @sobolevnrm pushed a new version tp PyPI, it automatically creates the PR for the conda-forge. Then we just review and do if there are any changes that need to be done. See https://github.com/conda-forge/pdb2pqr-feedstock for further details.

**Comment by sobolevnrm** [comment]
Thank you, @tsenapathi !
