### ISSUE TITLE
The PDB2PQR is not generating a .in file and is not enabling me to use the "use results on APBS" option

### ISSUE THREAD

**Issue by leofrancalima** [Electrostatics/pdb2pqr#215]
Dear APBS server team,

I hope this find you well,

I'm using the online server for pdb2qr and APBS calculations. 

When I submit my .pdb file to pdb2qr, the program run and finally return the "complete" comunication. However, just the respective .json, .txt, .log and .stdout.txt outputs are returned, without the generation of the .in file and without enabling the "use results on APBS" icon.

What can be wrong?

Thank you so much in advance. Looking forward for your reply.

Sincerely,
Leonardo.

**Comment by leofrancalima** [comment]
Oh, Still about the message above:

The .pqr file (the most important on this calculation) isn't being generated either. My job ID is rg9wf29e09.

Thank you so much.

**Comment by sobolevnrm** [comment]
@Eo300 can you please look into this?  Thanks.

**Comment by Eo300** [comment]
Hi @leofrancalima, after looking into your issue, it appears that the REMARK line in your PDB input is causing the parsing to fail.  According to the [format](http://www.wwpdb.org/documentation/file-format-content/format33/remarks.html), columns 8-10 of a REMARK should be a reference number, which would be an integer of your choosing. 

**Example:**
```
REMARK some text about this file      # Will cause parsing error
---
REMARK 1  some text about this file   # No parsing error. Note the two spaces after the '1' since PDB2PQR examines all text in columns 8-10
```

Your calculation should continue as expected after making this change to your PDB file, producing the output files you're looking for as well.

If these steps don't resolve your issue or you run into more troubles, please let us know. Thanks!

**Comment by leofrancalima** [comment]
Dear Elvis,

Thank you so much for your response. I have already removed this line from
the PDB and the process has been carried out correctly.

Thank you again,

Sincerely,

Leonardo Lima.



Em seg., 2 de ago. de 2021 às 14:21, Elvis ***@***.***>
escreveu:
