### ISSUE TITLE
HETATMs get renamed to ATOMs during processing

### ISSUE THREAD

**Issue by intendo** [Electrostatics/pdb2pqr#218]
During the processing, HETATMs get renamed to ATOMs in the resulting PQR file.

**Comment by sobolevnrm** [comment]
@intendo can you please provide an example that reproduces this issue?

**Comment by sobolevnrm** [comment]
This appears to be fixed when testing against [1FAS](https://www.rcsb.org/structure/1FAS) with the current commit (f23c0e6) of the master branch.
