### ISSUE TITLE
Suppress (or redirect to files) repeated logging messages

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/pdb2pqr#22]
See https://stackoverflow.com/questions/44691558/suppress-multiple-messages-with-same-content-in-python-logging-module-aka-log-co/44692178

**Comment by intendo** [comment]
@sobolevnrm, Did this get fixed with @bigdawgmj logging fixes?

**Comment by sobolevnrm** [comment]
Yes, I think so.
