### ISSUE TITLE
Fix "lazy" formatting in logging functions

### ISSUE THREAD

**Issue by intendo** [Electrostatics/pdb2pqr#222]
We were too eager to implement fstrings and went too far. The correct way to implement strings in logging functions is to use the lazy % formatting.

**Comment by sobolevnrm** [comment]
I think that is mainly for performance reasons, right?  The f-strings get evaluated even if the logging level is below the basicConfig setting?  If we're not seeing major performance problems, then this should be pretty low priority...

**Comment by intendo** [comment]
This is so low, I will only work on it while watching TV while holding a sleeping puppy :-)
