### ISSUE TITLE
API docs are not being built

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/pdb2pqr#224]
There's plenty of documentation (e.g., https://github.com/Electrostatics/pdb2pqr/blob/master/pdb2pqr/aa.py) but ReadTheDocs isn't building it (https://pdb2pqr.readthedocs.io/en/latest/api/aa.html).  The documentation builds fine locally with Sphinx.

**Comment by intendo** [comment]
I updated the Sphinx configuration on the `main` branch and increased the version to 3.2.1. The documents are now correctly built on ReadTheDocs.
