### ISSUE TITLE
PDB2PQR error with heme ligand

### ISSUE THREAD

**Issue by MR3300** [Electrostatics/pdb2pqr#229]
Hi,

I keep running into the same error, both running pdb2pqr locally and through the server. I am trying to calculate electrostatic surfaces for a heme containing protein. 

I extract and generate a .mol2 file for the heme ligand (HEC) using PRODRG, removing the iron atom and adding hydrogens beforehand and include this along with the .pdb file for the whole protein (+ HEC) when submitting the job either locally or on the server.  In both cases this is the error I get back:

"CRITICAL:Residue HEC 105 charge is non-integer: 34.8618
CRITICAL:Giving up."

Which I suspect is the result of a previous warning:

WARNING:PDB2PQR could not identify the following residues and residue numbers as returned by PROPKA or PDB2PKA

WARNING:             HEC  NA A
WARNING:             HEC CGA A
WARNING:             HEC  NB A
WARNING:             HEC  NC A
WARNING:             HEC  ND A
WARNING:             HEC CGD A

These same atoms are flagged earlier on in the log file:

INFO:Found NAR group:   828-  NA   105-HEC (A) [  44.854   26.575    7.169] N
INFO:Found OCO group:   836- CGA   105-HEC (A) [  45.165   23.630   12.392] C
INFO:Found NAR group:   839-  NB   105-HEC (A) [  45.380   27.146    4.404] N
INFO:Found NAR group:   847-  NC   105-HEC (A) [  44.378   29.757    4.719] N
INFO:Found NAR group:   855-  ND   105-HEC (A) [  43.902   29.128    7.459] N
INFO:Found OCO group:   863- CGD   105-HEC (A) [  40.197   29.179   12.181] C

I've tried modifying names in the pdb and .mol2 file to no avail. Does anyone have any suggestions as to what else I could try?

Regards,

M

**Comment by jbardhan** [comment]
Hi M,

Could you please attach the input file you're using?  (You'll need to change the file extension to .txt)

Thanks very much,
Jay

**Comment by MR3300** [comment]
Hi Jay,

Here are the input files are the resulting error files. I've tried lots of combinations of renaming residues in the pdb and mol2 but they pretty much all give the same error. This is a single heme protein and once I've resolved the issue I'm hoping to expand this to multiheme cytochromes (one step at a time).  

I have no doubt this is down to user-error but it you're able to point me in the right direction it'd be appreciated.

[Run2_1hrc_processed_pdb.txt](https://github.com/Electrostatics/pdb2pqr/files/7260772/Run2_1hrc_processed_pdb.txt)
[Run2_pdb2pqr.stderr.txt](https://github.com/Electrostatics/pdb2pqr/files/7260775/Run2_pdb2pqr.stderr.txt)
[Run2_PRODRG_HEC_edit_MOL2.txt](https://github.com/Electrostatics/pdb2pqr/files/7260779/Run2_PRODRG_HEC_edit_MOL2.txt)

**Comment by jbardhan** [comment]
Hello, thank you for sharing these!

I'll try as well.  We have seen a few "non-integer" errors over the last few weeks -- it may not be just user error.

Thanks very much,
Jay

**Comment by sobolevnrm** [comment]
The heme residue is the source of the non-integer charge.  However, since the heme should be covalently bonded to the protein, there should also be modifications to the protein structure that aren't considered by PDB2PQR.  In general, PDB2PQR is not able to handle covalently modified biomolecules.  Sorry, but I do not think this is fixable.
