### ISSUE TITLE
Ligands with mol2 files are displaced from the proper coordinates after assigning charges. 

### ISSUE THREAD

**Issue by JLaureantiPNNL** [Electrostatics/pdb2pqr#23]
Hello, 

I ran a job with the 3WIP acetylcholinesterase enzyme on both the old web server and the new updated web server. For this job I created a mol2 file for the ACH ligand using the PRODRG web tool and asked that parameters be generated for the ligand as well. When the job completes the XYZ coordinates for the ligand in the PQR file do not match that of the XYZ coordinates in the PDB file, and thus the ligand is no longer in the pocket. 

I also tested the 5GV7 system with a mol2 file for the ligand as well on both servers and the same result was observed, i.e. the ligand has moved from the proper coordinate position. 

With 1HPX and using chimera to generate a mol2 file, ligand is in the incorrect spot as well. Not as bad as the previous two examples I tried, but still not correct. 

Using 1ABF with a mol2 file for the ligand using the PRODRG web tool, leads to the ligand in the incorrect spot. 

Is there a way to keep the ligand in the correct spot??

**Comment by sobolevnrm** [comment]
@JLaureantiPNNL -- can you please check whether this still happens with the latest release https://github.com/Electrostatics/pdb2pqr/releases ?

**Comment by JLaureantiPNNL** [comment]
Hi Nathan,

No problem. I can do this sometime this week. I downloaded the pdb2pqr-2.1.1 release.

I’ll use the same examples I used before.

Cheers,
Joe

**Comment by sobolevnrm** [comment]
Thanks for troubleshooting this @JLaureantiPNNL !

PDB2PQR takes the coordinates from the mol2 file and not from the ligand in the pdb file.
 
Originally the system failed to place the ligand in the correct position when using the FAD_wrong.mol2 file (the product was 5gv7_wrong.pqr). Using a mol2 file with the coordinates exactly as they are in the pdb that is passed in (FAD_right.mol2) gives the product 5gv7_right.pqr.
 
This could be problematic if there are more than one ligand. Or if a general ligand is used as a “template”.

* [5gv7.pdb](https://gist.github.com/sobolevnrm/fbe4e3d5b7d6a1d6125b3fa9520ed711)
* [5gv7_wrong.pqr](https://gist.github.com/sobolevnrm/ef446decaa4f0ea88c3d5206789c25f4)
* [5gv7_right.pqr](https://gist.github.com/sobolevnrm/553c83627dcb3bf14a45e77d53fbe7ad)
* [FAD_wrong.mol2](https://gist.github.com/sobolevnrm/3b9d80bcc64daf398338de27d2b9fe98)
* [FAD_right.mol2](https://gist.github.com/sobolevnrm/e38664e6f934d80932bc319aa3ea6f6a)

**Comment by sobolevnrm** [comment]
More troubleshooting from @JLaureantiPNNL 

Following up a bit more. The coordinates of the ligand (for the pqr file) are taken from the mol2 file and not the pdb input file. This leads to PDB2PQR deleting a second instance of the ligand.
 
Double2.pqr was made using Double2.pdb and FAD_right.mol2 as inputs. Double2.pdb has two FAD molecules in different positions (the atoms and residues have different values). However, Double2.pqr only has one FAD molecule.  

* [FAD_right.mol2](https://gist.github.com/sobolevnrm/dfb6ac2ef76f7c87cec0aa257d1c7b6e)
* [Double2.pdb](https://gist.github.com/sobolevnrm/51382621d52c46c8e0ee1f1a63dfa521)
* [Double2.pqr](https://gist.github.com/sobolevnrm/3a18b2fcdaab1cd77a1a4f652126f231)

**Comment by sobolevnrm** [comment]
This is not straightforward to fix.  For now, I will just add more information to the documentation indicating that only one ligand can be used in a calculations.
