### ISSUE TITLE
pdd2pqr ligand problem

### ISSUE THREAD

**Issue by kva0987** [Electrostatics/pdb2pqr#230]
Hi,

I encountered some issues while trying to run pdb2pqr for APBS.

1. pdb2pqr cannot take am bond type from mol.2 file any more. I believe it was able to do that before.
2. WARNING:PDB2PQR could not identify the following residues and residue numbers as returned by PROPKA or PDB2PKA
WARNING:Can't find HETATM 627 1 N1 in MOL2 file
It says it cannot find TETATM in mol2 file.
So I used the same setup which used to work few months ago, but still giving the same error.

Could someone help on this?

**Comment by kva0987** [comment]
Job ID is zfh7fqlmwo_20210930

**Comment by jbardhan** [comment]
Hello,

Thank you for alerting us to this, and for submitting the job ID!

Do you recall (even if only roughly) when you remember pdb2pqr being able to take the bond type from a mol2 file?

Thanks very much,
Jay

**Comment by kva0987** [comment]
I had ran pdb2pqr this February and May. I did not recognize this kind of error then.

**Comment by jbardhan** [comment]
Thank you!  That's helpful.

Jay

**Comment by sobolevnrm** [comment]
@kva0987 Can you please provide the files you used with this calculation?  I'm going to close the issue until you post them.  Please feel free to reopen afterward.  Thanks.
