### ISSUE TITLE
Error running pdb2pqr with PyMol

### ISSUE THREAD

**Issue by mishaguy** [Electrostatics/pdb2pqr#236]
We're using pdb2pqr with PyMol. We install using pip and version is 3.2.0.
Seems it is the same version as on the web service of pdb2pqr.
When we run to prepare molecule via APBS plugin, we're getting error messages for many RNA molecules when we specify standard pdb2pqr method.
I tried to mimic options from pdb2pqr web service and got the same error.
Attached is the screenshot and below are details.
For now I instructed my users to use different method in PyMol instead of default pdb2pqr (for instance, when vdw is used, all works fine). However many biologists or medical researches do not want to go in details and like to have default option.
Any help on how to work around this issue would be greatly appreciated.
Thanks,
Misha

INFO:PDB2PQR v3.2.0: biomolecular structure conversion software.
INFO:Please cite:  Jurrus E, et al.  Improvements to the APBS biomolecular solvation software suite.  Protein Sci 27 112-128 (2018).
INFO:Please cite:  Dolinsky TJ, et al.  PDB2PQR: expanding and upgrading automated preparation of biomolecular structures for molecular simulations. Nucleic Acids Res 35 W522-W525 (2007).
INFO:Checking and transforming input arguments.
INFO:Loading topology files.
INFO:Loading molecule: C:\Users\misha\AppData\Local\Temp\tmp5xr4l4pw\in.pqr
INFO:Setting up molecule.
Traceback (most recent call last):
  File "c:\users\misha\appdata\local\programs\python\python36\lib\site-packages\pdb2pqr\biomolecule.py", line 965, in create_residue
    klass = getattr(aa, resname)
AttributeError: module 'pdb2pqr.aa' has no attribute 'RU'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\misha\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\misha\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\misha\AppData\Local\Programs\Python\Python36\Scripts\pdb2pqr30.EXE\__main__.py", line 7, in <module>
  File "c:\users\misha\appdata\local\programs\python\python36\lib\site-packages\pdb2pqr\main.py", line 811, in main
    _ = main_driver(args)
  File "c:\users\misha\appdata\local\programs\python\python36\lib\site-packages\pdb2pqr\main.py", line 754, in main_driver
    pdblist, definition, args.ligand
  File "c:\users\misha\appdata\local\programs\python\python36\lib\site-packages\pdb2pqr\main.py", line 401, in setup_molecule
    biomolecule = biomol.Biomolecule(pdblist, definition)
  File "c:\users\misha\appdata\local\programs\python\python36\lib\site-packages\pdb2pqr\biomolecule.py", line 91, in __init__
    residue, previous_atom.res_name
  File "c:\users\misha\appdata\local\programs\python\python36\lib\site-packages\pdb2pqr\biomolecule.py", line 967, in create_residue
    klass = getattr(na, resname)
AttributeError: module 'pdb2pqr.na' has no attribute 'RU'
<img width="503" alt="Screen Shot 2021-10-25 at 11 02 34 AM" src="https://user-images.githubusercontent.com/86742487/138721863-6be00170-72bd-4e94-bd95-9089bac5e822.png">

Forgot to mention a pdb code producing such error. 4e8m, for instance.
thanks

**Comment by sobolevnrm** [comment]
@mishaguy was this fixed in the recent PDB2PQR releases?

**Comment by mishaguy** [comment]
Hi Nathan,

Thanks for thinking about me.

First of all, it is not on the webserver where this error occurs. It is rather when I use pdb2pqr from PyMol plugin.

I have updated now to your 3.2.2 and no, it is still producing error with default pd2pqr method.

It is now actually producing more complicated error log than 3.2.0.
I have attached it here.

The structure producing error is for instance 4e8m.

Hope this will be resolved soon and thanks for the great tool you provide to research community.

Best,
Misha


Mikhael Guy
Research Scientist
Science Research Software Core
Yale Center for Research Computing
Yale University
P.O. Box 208107
Sterling Chemistry Laboratory
225 Prospect Street, Rm. 154
New Haven, CT 06520
203.436.8599
For questions related to scientific, analytical and computational software, please e-mail at ***@***.******@***.***>

On Nov 21, 2021, at 5:47 PM, Nathan Baker ***@***.******@***.***>> wrote:



@mishaguy<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmishaguy&data=04%7C01%7Cmikhael.guy%40yale.edu%7C11919d34704749d095a208d9ad40f82d%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637731317281642337%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0z3%2BnTj1NrNsyMgOdq5ldmzN%2BGWkV6vOj2bl0u783iM%3D&reserved=0> was this fixed in the recent PDB2PQR releases?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FElectrostatics%2Fpdb2pqr%2Fissues%2F236%23issuecomment-974911792&data=04%7C01%7Cmikhael.guy%40yale.edu%7C11919d34704749d095a208d9ad40f82d%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637731317281652331%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=a70yExnXDqIpgLN%2FSN05IwrrTIOYR9GRepdfLuKut3E%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUVZLV3RJOT4WJVWNPG3OE3UNFZJ7ANCNFSM5GVQ3M5Q&data=04%7C01%7Cmikhael.guy%40yale.edu%7C11919d34704749d095a208d9ad40f82d%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637731317281662325%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1iXbbytTWqTFNUDwp8RaKeR6VLJ9%2FRcszd%2FrYVX1poU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cmikhael.guy%40yale.edu%7C11919d34704749d095a208d9ad40f82d%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637731317281662325%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wIglOL6at5bDHbnuLCPKZJAFErx2Z%2F6hLTT4pmi9J0I%3D&reserved=0>.

**Comment by sobolevnrm** [comment]
Hi Misha --

It looks like we might have duplicate issues here.  Can you please close the one that's least relevant?

Regardless, I'm not very familiar with PyMOL and it is difficult for me to troubleshoot this.  I wonder if @speleo3 might have suggestions on who can help?

Do you know what version of Python PyMOL is using?

Thank you,

Nathan

**Comment by mishaguy** [comment]
Hi Nathan,
The other issue is not mine, I can't close it. You can stop e-mailing there.
I observe these problems in both Python 3.6 and Python 3.9.

One thing I'd like to tell you. Because of this error, we use different method - formal_charge_and_vdw.
With your new 3.2.2 the results in apbs are ore consistent with what we obtain on Mac where the old pdb2pqr version is still installed. See attached screenshot. Basically with 3.2.0 the picture looks the same but what is red is rather light green there meaning that esp is rather positive
<img width="534" alt="Screen Shot 2021-11-23 at 11 40 41 PM" src="https://user-images.githubusercontent.com/86742487/143176203-6e4f1a2c-0deb-4c53-973f-92ba3cffb76e.png">

Thanks,
Misha

**Comment by sobolevnrm** [comment]
@mishaguy that looks like a very strange surface potential for a protein... have you visualized it using the web server?

**Comment by mishaguy** [comment]
no, I have not used it with web server.
I tried it now and got errors with pdb2pqr.
can you check it on your side.
4e8m

**Comment by sobolevnrm** [comment]
Oh, I lost the thread here that this is a nucleic acid issue.  I'm going to create a new issue that's a bit more specific to replace this one.

**Comment by speleo3** [comment]
Issue moved to https://github.com/Electrostatics/pdb2pqr/issues/256
