### ISSUE TITLE
Swapped HD21/HD22 assignment for ASN

### ISSUE THREAD

**Issue by chemsh** [Electrostatics/pdb2pqr#242]
Dear PDB2PQR authors,

we find ASN's HD21/HD22 atom labels are swapped when PDB2PQR guesses the missing hydrogens' positions. According to the original CHARMM forcefield topology, for example top_all36_prot.rtf, HD21 is cis to OD1 while HD22 trans. Please see attached an example of P450 (_pdb2pqr.pdb). In the resulting structure _pdb2pqr.out.pdb all ASN HD21 atoms are trans and HD22 have become cis. The two hydrogens bare a bit different charges of 0.32 and 0.30, respectively, so that Coulombic energy will be calculated with a deviation. We appreciate if you could take a look and fix the issue. Many thanks.

Kind regards,

You

**Comment by chemsh** [comment]
[p450_pqd2pqr.tar.gz](https://github.com/Electrostatics/pdb2pqr/files/7465407/p450_pqd2pqr.tar.gz)

**Comment by sobolevnrm** [comment]
Hi @chemsh -- thank you for reporting this.  We will investigate.

**Comment by chemsh** [comment]
@sobolevnrm Brilliant! Thank you very much.
