### ISSUE TITLE
Add PDB2PQR 3.3.1 to web server

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/pdb2pqr#248]
@Eo300 and @intendo -- can we get 3.3.1 integrated into the webserver?  Thanks.

_Originally posted by @sobolevnrm in https://github.com/Electrostatics/pdb2pqr/issues/211#issuecomment-968202095_

**Comment by intendo** [comment]
We will work with @mmacduff to update the documentation and get this deployed.

**Comment by intendo** [comment]
This was fixed via https://github.com/Electrostatics/apbs-aws/pull/139
PDB2PQR was updated to 3.3.1 on dev, test, and production deployments on AWS.
