### ISSUE TITLE
pdb files with >999 residues are not processed correctly

### ISSUE THREAD

**Issue by RayHackett** [Electrostatics/pdb2pqr#250]
For proteins with more than 1000 pdb2pqr gives a warning for each titratable residue beyond residue number 1000:
pdb2pqr.stderr.txt contains the following lines:
WARNING:PDB2PQR could not identify the following residues and residue numbers as returned by PROPKA or PDB2PKA
WARNING:             ASP1006 A
[...]

I suspect this is due to the fact that in .pdb file format once the residue number reaches 1000 there is no space between chain identifier (column 22 and residue number (columns18-20).

Webserver Example Job ID: lmdy0xmvat_20211119

**Comment by sobolevnrm** [comment]
This issue can be reproduced on the command line with:
```
 pdb2pqr30 --with-ph 7.0 --keep-chain --titration-state-method propka 1000-residues.pdb foo.pqr
```
where 1000-residues.pdb is provided in 
[1000-residues.zip](https://github.com/Electrostatics/pdb2pqr/files/7575584/1000-residues.zip).

**Comment by sobolevnrm** [comment]
I think this problem originates with [https://github.com/jensengroup/propka](PROPKA) incorrectly parsing PDBs with more than 999 residues.

However, PDB2PQR is also not double-checking the results from PROPKA to avoid this error.

**Comment by sobolevnrm** [comment]
> 

Actually, the problem is **not** with PROPKA.  The problem is how PDB2PQR assembles the pKa dictionary in [main.py:nontrivial](https://github.com/Electrostatics/pdb2pqr/blob/6250bcf28fde4913b8fdf9d13cedd1a38ed7499c/pdb2pqr/main.py#L583).

**Comment by RayHackett** [comment]
After testing with my some .pbd files with more than 999 residues the problem still seems to persist. Both using the webserver and using a local version of the newest commit still bring up the same warnings.
WARNING:biomolecule.py:909:apply_pka_values:PDB2PQR could not identify the following residues and residue numbers as returned by PROPKA or PDB2PKA
WARNING:biomolecule.py:912:apply_pka_values:             ARG1013 A
[...]

Thank you for attending to this issue so quickly!

**Comment by sobolevnrm** [comment]
@RayHackett - the web server has not been upgraded yet.  Can you test this using the command-line tool?

@intendo - can you please update the web server?

**Comment by RayHackett** [comment]
yes it is reproducible with the newest local version too. (I checked - and yes my version does have the applied changes to biomolecules.py and main.py

the command and file you supplied above reporduce the issue aswell
pdb2pqr30 --with-ph 7.0 --keep-chain --titration-state-method propka 1000-residues.pdb foo.pqr

**Comment by sobolevnrm** [comment]
I won't be able to look at this until later today or during the holidays.  Sorry.

**Comment by RayHackett** [comment]
No worries. Thank you for helping!

**Comment by intendo** [comment]
@sobolevnrm should we wait to upgrade the web server(s) until the underlying problem is fixed?

**Comment by RayHackett** [comment]
I'm sorry that was my mistake! I'm terribly sorry, you have indeed fixed the error.
I just discovered that depending on which conda environment I was in I was unknowingly using an old version of pdb2pqr (3.2.0) which had been installed as part of a different program.
When finally referencing to the correct and newest installation of pdb2pqr the warnings disappeared.
I think it should be fine to update the server with the current commit too.
Thank you for your patience and your help!

**Comment by intendo** [comment]
@sobolevnrm I updated the test, dev, and prod web servers to use pdb2pqr 3.3.2.

**Comment by sobolevnrm** [comment]
I truly thought I was losing my mind... and feel much much better now.  Thank you, @RayHackett !

> I'm sorry that was my mistake! I'm terribly sorry, you have indeed fixed the error. I just discovered that depending on which conda environment I was in I was unknowingly using an old version of pdb2pqr (3.2.0) which had been installed as part of a different program. When finally referencing to the correct and newest installation of pdb2pqr the warnings disappeared. I think it should be fine to update the server with the current commit too. Thank you for your patience and your help!

**Comment by sobolevnrm** [comment]
> @sobolevnrm I updated the test, dev, and prod web servers to use pdb2pqr 3.3.2.

Thank you, @intendo !
