### ISSUE TITLE
PDB2PQR fails on files with only nucleic acid resides

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/pdb2pqr#256]
On structures like [4E8M](https://www.rcsb.org/structure/4E8M), PDB2PQR fails with messages like:
```
2021-11-25 15:51:05,865 CRITICAL:main.py:791:main_driver:No biomolecule heavy atoms found and no ligand present. Unable to proceed.  You may also see this message if PDB2PQR does not have parameters for any residue in your biomolecule.
2021-11-25 15:51:05,866 CRITICAL:main.py:792:main_driver:Giving up.
```

Reported by @mishaguy.

**Comment by sobolevnrm** [comment]
This problem appears to be specific to RNA-only PDB entries.  For example, [1NAJ](https://www.rcsb.org/structure/1NAJ) seems to work in the test created in af3caec.

The source of the issue is an inconsistency between [`NA.xml`](https://github.com/Electrostatics/pdb2pqr/blob/master/pdb2pqr/dat/NA.xml) and [PDB nomenclature for nucleic acids](https://pdb101.rcsb.org/learn/guide-to-understanding-pdb-data/primary-sequences-and-the-pdb-format).  The former uses `RA`, `RC`, `RG`, `RU` and the latter uses `A`, `C`, `G`, `U`.

**Comment by mishaguy** [comment]
the previous versions of pdb2pqr handled these structures without error.
I still have it attached to my PyMol on Mac, I get it from Homebrew, and it works without error

**Comment by sobolevnrm** [comment]
The `ANISOU` records in [4E8M](https://www.rcsb.org/experimental/4E8M) appear to be part of the problem.  After fixing the problem with residue naming (PDB2PQR was expecting `RA`, etc. and the PDB file had `A`, etc.), the RNA structure [5V0O](https://www.rcsb.org/structure/5V0O) without `ANISOU` records works but 4E8M does not.

**Comment by sobolevnrm** [comment]
> The `ANISOU` records in [4E8M](https://www.rcsb.org/experimental/4E8M) appear to be part of the problem. After fixing the problem with residue naming (PDB2PQR was expecting `RA`, etc. and the PDB file had `A`, etc.), the RNA structure [5V0O](https://www.rcsb.org/structure/5V0O) without `ANISOU` records works but 4E8M does not.

Err... that's not correct:  grepping the `ANISOU` records out of 4E8M still gives a file that generates errors in my "fixed" version of PDB2PQR.

**Comment by sobolevnrm** [comment]
It looks like the problems I'm seeing with 4E8M now are due to PDB2PQR incorrectly reconstructing missing atoms:
```
REMARK 470   M RES CSSEQI  ATOMS                                                
REMARK 470       G A  -1    OP2  N9   C8   N7   C5   C6   O6                    
REMARK 470       G A  -1    N1   C2   N2   N3   C4                              
REMARK 470       G A   1    N9   C8   N7   C5   C6   O6   N1                    
REMARK 470       G A   1    C2   N2   N3   C4                                   
REMARK 470       A A 207    N9   C8   N7   C5   C6   N6   N1                    
REMARK 470       A A 207    C2   N3   C4                                        
REMARK 470       G A 311    N9   C8   N7   C5   C6   O6   N1                    
REMARK 470       G A 311    C2   N2   N3   C4                                   
REMARK 470       C A 312    N1   C2   O2   N3   C4   N4   C5                    
REMARK 470       C A 312    C6                                                  
REMARK 470       G A 391    N9   C8   N7   C5   C6   O6   N1                    
REMARK 470       G A 391    C2   N2   N3   C4
```

**Comment by sobolevnrm** [comment]
This appears to be a separate problem so I've created a new issue (#267) for it.
