### ISSUE TITLE
PDB2PQR not working with 4E8P and 6T3R

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/pdb2pqr#283]
@mishaguy reported that [4E8P](https://www.rcsb.org/structure/4E8P) and [6T3R](https://www.rcsb.org/structure/6T3R) do not work with the current version of PDB2PQR.

**Comment by sobolevnrm** [comment]
Running [48EP](https://www.rcsb.org/structure/4E8P) with PDB2PQR v3.5.0 gives the following error:
```
CRITICAL:Too few atoms present to reconstruct or cap residue RG A 390 in structure! This error is generally caused by missing backbone atoms in this biomolecule; you must use an external program to complete gaps in the biomolecule backbone. Heavy atoms missing from RG A 390:  C5' C4' O4' C1' N9 C8 N7 C5 C6 O6 N1 C2 N2 N3 C4 C3' C2' O2' O3' O5'
CRITICAL:Giving up.
```
This is consistent with the comments in the 4E8P PDB file that lists these atoms among those missing in the structure:
```
REMARK 470                                                                      
REMARK 470 MISSING ATOM                                                         
REMARK 470 THE FOLLOWING RESIDUES HAVE MISSING ATOMS (M=MODEL NUMBER;           
REMARK 470 RES=RESIDUE NAME; C=CHAIN IDENTIFIER; SSEQ=SEQUENCE NUMBER;          
REMARK 470 I=INSERTION CODE):                                                   
REMARK 470   M RES CSSEQI  ATOMS                                                
REMARK 470       G A  -1    OP2  N9   C8   N7   C5   C6   O6                    
REMARK 470       G A  -1    N1   C2   N2   N3   C4                              
REMARK 470       G A   1    N9   C8   N7   C5   C6   O6   N1                    
REMARK 470       G A   1    C2   N2   N3   C4                                   
REMARK 470       G A 390    O5'  C5'  C4'  O4'  C3'  O3'  C2'                   
REMARK 470       G A 390    O2'  C1'  N9   C8   N7   C5   C6                    
REMARK 470       G A 390    O6   N1   C2   N2   N3   C4
```
There are too many atoms missing from this residue for PDB2PQR to reconstruct.  Therefore, the failure is expected and is not a bug.

**Comment by sobolevnrm** [comment]
Running [6T3R](https://www.rcsb.org/structure/4E8P) with PDB2PQR v3.5.0 gives the following error:
```
CRITICAL:Too few atoms present to reconstruct or cap residue RG A 390 in structure! This error is generally caused by missing backbone atoms in this biomolecule; you must use an external program to complete gaps in the biomolecule backbone. Heavy atoms missing from RG A 390:  C5' C4' O4' C1' N9 C8 N7 C5 C6 O6 N1 C2 N2 N3 C4 C3' C2' O2' O3' O5'
CRITICAL:Giving up.
```
This is consistent with the comments in 6T3R PDB file that lists these atoms among those missing in the structure:
```
REMARK 470                                                                      
REMARK 470 MISSING ATOM                                                         
REMARK 470 THE FOLLOWING RESIDUES HAVE MISSING ATOMS (M=MODEL NUMBER;           
REMARK 470 RES=RESIDUE NAME; C=CHAIN IDENTIFIER; SSEQ=SEQUENCE NUMBER;          
REMARK 470 I=INSERTION CODE):                                                   
REMARK 470   M RES CSSEQI  ATOMS                                                
REMARK 470       G A 390    O5'  C5'  C4'  O4'  C3'  O3'  C2'                   
REMARK 470       G A 390    O2'  C1'  N9   C8   N7   C5   C6                    
REMARK 470       G A 390    O6   N1   C2   N2   N3   C4
```
There are too many atoms missing from this residue for PDB2PQR to reconstruct. Therefore, the failure is expected and is not a bug.

**Comment by sobolevnrm** [comment]
Neither of these failures results from a bug in PDB2PQR so I am closing this issue.

**Comment by mishaguy** [comment]
I am not sure about why pdb2pqr can't do this job here. I am not the expert.
If I use formal charge and vdw in PyMol instead of pdb2pqr, I am getting result. See attached surface. I am not sure that this is actually correct surface. I asked this question before, why is it so positive?
In 4e8m which you fixed a day ago, the results with pdb2pqr and with formal charge and vdw are visibly identical.
<img width="566" alt="Screen Shot 2022-01-01 at 10 48 33 PM" src="https://user-images.githubusercontent.com/86742487/147865792-86d155be-ab9e-4531-8e63-63fd4fc46f28.png">

**Comment by sobolevnrm** [comment]
The problems with 4E8P and 6T3R are not bugs in PDB2PQR so this issue is closed.  If you want to continue this discussion, please do so [here](https://github.com/Electrostatics/pdb2pqr/discussions/285).
