### ISSUE TITLE
New PDB2PQR release

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/pdb2pqr#292]
If you approve this, would be awesome if you can make quickly a bug-fix release as well so that I can get rid of my really ugly workaround :smiley:

_Originally posted by @stefdoerr in https://github.com/Electrostatics/pdb2pqr/issues/291#issuecomment-1014384347_

* [ ] Need to update releases.rst
* [ ] Usual updates on version number, etc.

**Comment by stefdoerr** [comment]
For me it's done. I don't have any further issues with the merged PRs so if you want to make a new release go ahead.

**Comment by sobolevnrm** [comment]
https://pypi.org/project/pdb2pqr/3.5.2/

**Comment by stefdoerr** [comment]
To not bother you excessively with releases we have decided to create our own patch releases on https://anaconda.org/acellera/pdb2pqr They get post-fixed with +X where X the patch version.
All our changes will be contributed to your repo as PRs so that we do not diverge.
Thanks!

**Comment by intendo** [comment]
@stefdoerr would it be possible to take the approach of creating a test that fails and then fixing/adding the code to make the test pass? This would make it easier for us to verify code coverage and maintain regression testing.

**Comment by stefdoerr** [comment]
Yes sure, I can start adding tests. I tend to add them to our repo but can definitely add here as well.

**Comment by stefdoerr** [comment]
Hi, sorry to revive this but could we have a new release of pdb2pqr with the patches which were merged during 2022? It would help us to avoid using our patch-fix package in https://anaconda.org/acellera/pdb2pqr and use your official one.
