### ISSUE TITLE
atomic radius

### ISSUE THREAD

**Issue by lex1213** [Electrostatics/pdb2pqr#311]
In an attempt to rebuild missing atoms in my input pdb file, the output pqr is giving multiple atoms with charge, but zero radius. What could be causing this?

**Comment by sobolevnrm** [comment]
Which atoms?  Can you please provide the input PDB and the output PQR?

**Comment by lex1213** [comment]
Hydrogens specifically on side chains of tyrosine, threonine and serine. Please see attached for the PDB and PQR files.

Alexis Dispensa
Doctoral Student
Graduate School of Biomedical Sciences
Rowan University
Phone: (347) 452-4474


From: Nathan Baker ***@***.***>
Reply-To: Electrostatics/pdb2pqr ***@***.***>
Date: Friday, April 22, 2022 at 10:44 PM
To: Electrostatics/pdb2pqr ***@***.***>
Cc: "Dispensa, Alexis" ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [Electrostatics/pdb2pqr] atomic radius (Issue #311)


Which atoms? Can you please provide the input PDB and the output PQR?
