### ISSUE TITLE
Error reading four letters residues

### ISSUE THREAD

**Issue by alexmcff** [Electrostatics/pdb2pqr#312]
I have a protein with a phosphorylated serine and I noticed there is an entry for PiSER in CHARMM.DAT that is called SEP1. However when I change my residue name in the pdbfile to SEP1 the server reads only SEP giving an error. 

Any help would be appreciated

**Comment by sobolevnrm** [comment]
Can you please upload an example?  I'll reopen the issue after you upload.  Thank you.
