### ISSUE TITLE
Biomolecue charge is non-integer --- pdb:4yki

### ISSUE THREAD

**Issue by khelmy55** [Electrostatics/pdb2pqr#319]
i have got an issue with a protein, PDB: 4yki
i pre-treated it with pdb4amber and tleap, ran pdb2pqr from the command line and here is what i got:

CRITICAL:Biomolecue charge is non-integer: -32.34
CRITICAL:Giving up.

**Comment by sobolevnrm** [comment]
The problem appears to be the GLY ligand.  When I deleted that from the structure, the PDB2PQR calculation proceeded without problem.

We do not have plans to fix the issue with the peptide ligand.
