### ISSUE TITLE
Cannot add --display-coupled-residues flag to PDB2PQR webserver

### ISSUE THREAD

**Issue by rediaz111** [Electrostatics/pdb2pqr#320]
I'm reviewing my results from running a PDB file through PDB2PQR and I find this message.
``Coupled residues (marked *) were detected.Please rerun PropKa with the --display-coupled-residues or -d option for detailed information.``

However, there is no option to pass this flag on the webserver.

**Comment by sobolevnrm** [comment]
Hello -- you will need to use the command line version of [PDB2PQR](https://github.com/Electrostatics/pdb2pqr) or [PROPKA](https://github.com/jensengroup/propka) to use this option.  Thank you.
