### ISSUE TITLE
Ligand with Amide Bonds

### ISSUE THREAD

**Issue by GeorgianaLiang** [Electrostatics/pdb2pqr#325]
Dear pdb2pqr developers:
I am looking to assign charges to a receptor considering the ligands bound to the receptor. I collected the needed files from PDB. However, the program tells me that the ligand (NAG) has an amide bond, which is not accepted by the program. Is there a way to go around this constraint? Thank you so much in advance!

**Comment by GeorgianaLiang** [comment]
I was using the PDB file 5kxi from the PDB website (with the sodium and nicotine removed). The problem arise with the NAG ligand (I converted from PDB to mol2 using a third-party program). The exact error message is "NotImplementedError: PDB2PQR does not currently support the amide (am) bond type".

**Comment by sobolevnrm** [comment]
![image](https://user-images.githubusercontent.com/1933272/185718041-b067729c-46eb-4b30-b68c-e23c0307ec49.png)

Because the NAG ligand contains an amide bond, PDB2PQR will not be able to assign charges to it.  I recommend removing that ligand from the structure.
