### ISSUE TITLE
Problems with Mn ion in enzyme

### ISSUE THREAD

**Issue by mverissi** [Electrostatics/pdb2pqr#333]
Hi all,

I am trying to use the pdb2pqr server to prepare a polymerase which has one ligand (a deoxy-triphosphate) and three metal ions (2 Mn2+ and 1 Mg2+) in its active site (PDB code 5omf). I have exported the DTP and the two metal ions to a MOL2 file, but I get the following error when the pdb2pqr server starts the ligands' parametrization:

`KeyError: "Unable to find radius parameter for self of type Mn in radius dictionary: {'C': 1.87, 'H': 1.1, 'O.co2': 1.76, 'N': 1.4, 'S': 2.15, 'F': 2.4, 'Cl': 1.82, 'I': 2.65}"`

Is it possible to run pdb2pqr for this enzyme? I am attaching the enzyme and ligand files to this post (with a `txt`suffix added, since Github doesn't accept mol2 or pdb files as attachments), as well as the `pdb2pqr.stderr.txt` file, in the hope it helps.

Best regards,

Marcos Verissimo Alves
Lund University

[pdb2pqr.stderr.txt](https://github.com/Electrostatics/pdb2pqr/files/10345178/pdb2pqr.stderr.txt)
[5omf_noligs.pdb.txt](https://github.com/Electrostatics/pdb2pqr/files/10345198/5omf_noligs.pdb.txt)
[ligands.mol2.txt](https://github.com/Electrostatics/pdb2pqr/files/10345199/ligands.mol2.txt)

**Comment by sobolevnrm** [comment]
We do not currently support the Mn ion.  You could try to add it to PDB2PQR using the instructions [in the documentation](https://pdb2pqr.readthedocs.io/en/latest/extending.html#adding-new-forcefield-parameters); however, please be aware that this will only add the charge contribution to output PQR file and will not influence the titration process, etc.
