### ISSUE TITLE
New PDB2PQR release

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/pdb2pqr#335]
Hi, sorry to revive this but could we have a new release of pdb2pqr in conda-forge https://anaconda.org/conda-forge/pdb2pqr with the patches which were merged during 2022? It would help us to avoid using our patch-fix package in https://anaconda.org/acellera/pdb2pqr and use your official one.

_Originally posted by @stefdoerr in https://github.com/Electrostatics/pdb2pqr/issues/292#issuecomment-1408286717_

**Comment by sobolevnrm** [comment]
I will work on this after https://github.com/jensengroup/propka/issues/153.

**Comment by sobolevnrm** [comment]
- [ ] Update `setup.py` to force latest version of PROPKA
- [ ] Update ChangeLog with changes since last release

**Comment by sobolevnrm** [comment]
https://github.com/Electrostatics/pdb2pqr/releases/tag/v3.6.0

**Comment by sobolevnrm** [comment]
@stefdoerr please see [release 3.6.0](https://github.com/Electrostatics/pdb2pqr/releases/tag/v3.6.0).

**Comment by stefdoerr** [comment]
Hi, just wanted to ask if there is a plan to also release to conda-forge?

**Comment by stefdoerr** [comment]
I posted a question here for now: https://github.com/conda-forge/pdb2pqr-feedstock/issues/12

**Comment by sobolevnrm** [comment]
Thank you, @stefdoerr !

**Comment by stefdoerr** [comment]
@sobolevnrm do we need to wait for the second reviewer for the PR to be merged? I'm not sure on how conda-forge works.

**Comment by sobolevnrm** [comment]
I don't think we need to wait; thank you.

**Comment by sobolevnrm** [comment]
This has been merged.

**Comment by stefdoerr** [comment]
I mean the conda-forge PR https://github.com/conda-forge/pdb2pqr-feedstock/pull/13
https://anaconda.org/conda-forge/pdb2pqr

**Comment by sobolevnrm** [comment]
Sorry; I've merged that one, too.  I'm still a big PIP fan and need to spend more time to learn conda.  Thank you for your help.
