### ISSUE TITLE
Run pdb2pqr as python library

### ISSUE THREAD

**Issue by dargen3** [Electrostatics/pdb2pqr#338]
Hello,

I'd like to thank you for pdb2pqr. It's a great tool! I would like to ask for your help. I am using pdb2pqr30 to protonate the structure using bash command:

`pdb2pqr30 --log-level DEBUG --noopt --titration-state-method propka --with-ph <ph> --pdb-output <pdb_output> <pdb_input> <pqr_file> 
`
Could you please guide me how to execute this command using the python API described by https://pdb2pqr.readthedocs.io/en/latest/api/index.html? I've tried it for hours with no results. You can also add this as an example on the API web page. I think enough users would appreciate it.

Regards,
Ondrej

**Comment by sobolevnrm** [comment]
Can you please share the code you've written so far and the problems you have encountered?

**Comment by kiyoon** [comment]
I think this can be closed as #410 introduced direct python call
