### ISSUE TITLE
pdb2pqr runs not deterministic

### ISSUE THREAD

**Issue by tonigi** [Electrostatics/pdb2pqr#35]
Apparently pdb2pqr results depend on hash ordering, which is platform-dependent.  If you run 3PTB with -R (randomize hashes), HIS 91 turns out to be HID/HIE at random (roughly 50%).  This becomes an issue under Python 3, which has random hashes on by default.

To check:

```
for i in `seq 10`; do python2 -R main.py  --with-ph=7.0 --ff=parse 3PTB.pdb py2-$i.pqr; done
grep -c "HD1 HIS    91" py2-*.pqr
```

T

**Comment by sobolevnrm** [comment]
The `-R` option is no longer supported so I am closing this issue.
