### ISSUE TITLE
Residues being renamed TER

### ISSUE THREAD

**Issue by quockerwodger** [Electrostatics/pdb2pqr#359]
I recently used the PDB2PQR webserver to create a pqr file for a protein complex I'm studying. However, when I looked at the pqr file I noticed a handful of residues had been renamed TER, but only a few atoms within each residue.

Here is an example of an Alanine that was altered:

In the original pdb, it was:
ATOM      1  N   ALA A   1     -26.208 -20.126   3.476  1.00 28.16           N  
ATOM      2  H   ALA A   1     -26.307 -21.011   3.000  1.00 28.16           H  
ATOM      3  H2  ALA A   1     -26.863 -20.097   4.244  1.00 28.16           H  
ATOM      4  H3  ALA A   1     -26.421 -19.386   2.824  1.00 28.16           H  
ATOM      5  CA  ALA A   1     -24.825 -19.995   3.982  1.00 28.16           C  
ATOM      6  HA  ALA A   1     -24.728 -19.046   4.509  1.00 28.16           H  
ATOM      7  C   ALA A   1     -23.816 -19.979   2.816  1.00 28.16           C  
ATOM      8  CB  ALA A   1     -24.561 -21.126   4.990  1.00 28.16           C  
ATOM      9  HB1 ALA A   1     -25.288 -21.082   5.801  1.00 28.16           H  
ATOM     10  HB2 ALA A   1     -23.564 -21.010   5.415  1.00 28.16           H  
ATOM     11  HB3 ALA A   1     -24.627 -22.097   4.499  1.00 28.16           H  
ATOM     12  O   ALA A   1     -22.928 -20.823   2.773  1.00 28.16           O 

But in the pqr it changed to:
ATOM      1  N   TER A   1     -26.208 -20.126   3.476 -0.3000 1.8500
ATOM      2  CA  TER A   1     -24.825 -19.995   3.982  0.2100 2.2750
ATOM      3  C   ALA A   1     -23.816 -19.979   2.816  0.5100 2.0000
ATOM      4  CB  ALA A   1     -24.561 -21.126   4.990 -0.2700 2.0600
ATOM      5  O   ALA A   1     -22.928 -20.823   2.773 -0.5100 1.7000
ATOM      6  HT1 TER A   1     -26.597 -19.218   3.330  0.3300 0.2245
ATOM      7  HA  TER A   1     -24.748 -19.129   4.481  0.1000 1.3200
ATOM      8  HB1 ALA A   1     -25.232 -21.071   5.725  0.0900 1.3200
ATOM      9  HB2 ALA A   1     -24.641 -22.004   4.524  0.0900 1.3200
ATOM     10  HB3 ALA A   1     -23.642 -21.023   5.363  0.0900 1.3200
ATOM     11  HT2 TER A   1     -26.200 -20.627   2.612  0.3300 0.2245
ATOM     12  HT3 TER A   1     -26.761 -20.622   4.144  0.3300 0.2245

**Comment by sobolevnrm** [comment]
Hello --

Depending on your force field, this should be the expected behavior (especially with default PDB2PQR settings).  The atoms involved in the amino terminus are labeled TER since their parameters are different than the amino group when it is bonded to another amino acid in the peptide chain.

Thanks
