### ISSUE TITLE
Validation of protonation states in the output PDB File

### ISSUE THREAD

**Issue by samit1194** [Electrostatics/pdb2pqr#362]
Hi All,

I understand that the PDB2PQR uses propka on the backend to determine the protonations states. I wanted to know once the file is generated using PDB2PQR using AMBER FF, why doesn't it rename the residues? Like ASP should be renamed as ASH and likewise for other residues.

Also Please elaborate on what is the logic here.

**Comment by sobolevnrm** [comment]
Hello --

You need to set both the force field and the output naming scheme:

![image](https://github.com/Electrostatics/pdb2pqr/assets/1933272/b8b5b4d4-e91c-4315-8dc9-359e1a28689f)

Thank you,

Nathan
