### ISSUE TITLE
build: adopt type checker (basedpyright), change linter/formatter/isort to ruff

### ISSUE THREAD

**Issue by kiyoon** [Electrostatics/pdb2pqr#406]
1. Static type checker is a very modern tool that enables analyzing python variables types and prevent errors before they are executed. I suggest to use pylance (for VScode) and basedpyright (for every other IDEs). It will encourage us to add types to the project overall, and greatly improve the development experience.

2. Instead of black/flake8/pylint, we can adopt `ruff` to make it much faster and handle everything with fewer dependencies and configurations.

**Comment by sobolevnrm** [comment]
This issue is fine to address if it doesn't change the format of too many files (e.g., preserves the format already in place with black/flake8.  However, I will not accept a PR on this if it needlessly changes the format of the source files.  Thanks!

**Comment by kiyoon** [comment]
@sobolevnrm I think that ruff and black is 99% compatible, but the line length setting is set to 79 here and normal black/ruff usually go by 88. So, if we change to 88 it will change much and if we leave to 79 it won't. So you prefer 79, right?

**Comment by sobolevnrm** [comment]
Yes, let's keep the line length to 79.  Thanks!

**Comment by kiyoon** [comment]
OK, I changed the #409 to use line-length of 79. The formatting didn't change much, but applying isort did change a bit of files.

**Comment by kiyoon** [comment]
Closed as completed in #409. We still need to address some new lint issues and add typings.
