### ISSUE TITLE
Remove __future__ annotations from Python files

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/pdb2pqr#417]
Note that `__future__ annotations` is not required anymore in all files.

_Originally posted by @kiyoon in https://github.com/Electrostatics/pdb2pqr/issues/414#issuecomment-2562173111_

**Comment by sobolevnrm** [comment]
@kiyoon do you want me to address this in a new PR or should it be added to your existing PR #412 ?

**Comment by kiyoon** [comment]
I can update that

**Comment by sobolevnrm** [comment]
@kiyoon is https://github.com/Electrostatics/pdb2pqr/blob/5ebbae457014cc25873978a8b8a5f0cdbda10f5b/pdb2pqr/residue.py#L7 still needed?

**Comment by kiyoon** [comment]
@sobolevnrm That's already removed just now, right?

**Comment by sobolevnrm** [comment]
You're right:  I checked the wrong version of the master branch.
