### ISSUE TITLE
PDB2PQR Unable to load parameter file for forcefield

### ISSUE THREAD

**Issue by kozlac** [Electrostatics/pdb2pqr#6]
PDB2PQR fails to find the `dat` folder when running from outside the source folder with error:
`
$ raise RuntimeError("Unable to load parameter file for forcefield %s" % args.ff)
`
`
$ RuntimeError: Unable to load parameter file for forcefield charmm
`

**Comment by sobolevnrm** [comment]
This issue was resolved a while ago (can't find specific commit number...).
