### ISSUE TITLE
Attribute error: Nonetype object has no attribute get_potentials

### ISSUE THREAD

**Issue by arikat** [Electrostatics/pdb2pqr#64]
Hi, We are using pdb2pqr 2.1.1 (latest version) and python2 with Ubuntu 18. We're getting the following error when invoking the --ph-calc-method=pdb2pka method. It does run for a long period of time and while it is calculating pkas, it eventually runs into this issue Picture attached.

![Unknown](https://user-images.githubusercontent.com/43094075/86807386-d19a9000-c047-11ea-83c4-643758251827.png)

**Comment by sobolevnrm** [comment]
Hi @arikat -- 

I am sorry about the problems that you've been experiencing.  We are working on refactoring PDB2PQR to address this type of problem.  In the meantime, are the PROPKA titration options in PDB2PQR suitable for your purposes?

Thank you,

Nathan
