### ISSUE TITLE
Installation problems and internal errors

### ISSUE THREAD

**Issue by Valdes-Tresanco-MS** [Electrostatics/pdb2pqr#65]
PDB2PQR is available in PyPi and great, however installing it from here leads to errors.
When I install it from here I get this error:

```
from .pdbx.reader.PdbxReader import PdbxReader
ModuleNotFoundError: No module named 'pdb2pqr.pdbx'
```
Apparently, the pdbx module is missing. In requirements.txt it appears as dependency mmcif_pdbx, however it doesn't seem to work. From what I appreciate here, the pdbx module itself is imported as a sub-module of pdb2pqr and also with relative import. Would it be wise to add the pdbx sub-module here or is there a specific way to install it from this repository?

The module installed from PyPi contains errors (two, according to this example). My command line was as follows:
`python.exe pdb2pqr\path\ __ main__.py --ff AMBER --with-ph 7.4 4fkk.pdb 4fkk.pqr`
This because 
`pdb2pqr30.exe` in python\Script get error
```
Traceback (most recent call last):
  File "lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "Scripts\pdb2pqr30.exe\__main__.py", line 7, in <module>
TypeError: main() missing 1 required positional argument: 'args'
```
Error 1:
```
File "pdb2pqr\main.py", line 502, in non_trivial
    matched_atoms = hitlist + lig_atoms
UnboundLocalError: local variable 'lig_atoms' referenced before assignment
```
This error occurs because lig_atoms only exists if the ligand was defined.
https://github.com/Electrostatics/pdb2pqr/blob/master/pdb2pqr/main.py#L477-502
 It can be fixed as follows:
```
    matched_atoms = hitlist + lig_atoms
else:
    matched_atoms = hitlist
```
Finally, when i fixed previous error get another small error:
```
File "pdb2pqr\main.py", line 531, in non_trivial
    protein.pdblist, missing_atoms, reslist, charge, args.ff,
UnboundLocalError: local variable 'missing_atoms' referenced before assignment
```
This error can be fixed changing `missing_atoms` definition from https://github.com/Electrostatics/pdb2pqr/blob/master/pdb2pqr/main.py#L481 to https://github.com/Electrostatics/pdb2pqr/blob/master/pdb2pqr/main.py#L476

Both error solution look like this in https://github.com/Electrostatics/pdb2pqr/blob/master/pdb2pqr/main.py#L476-502 :
```
    missing_atoms = []
    if args.ligand is not None:
        _LOGGER.info("Processing ligand.")
        _LOGGER.warning("Using ZAP9 forcefield for ligand radii.")
        ligand.assign_parameters()
        
        lig_atoms = []
        for residue in protein.residues:
            tot_charge = 0
            for pdb_atom in residue.atoms:
                # Only check residues with HETATM
                if pdb_atom.type == "ATOM":
                    break
                try:
                    mol2_atom = ligand.atoms[pdb_atom.name]
                    pdb_atom.radius = mol2_atom.radius
                    pdb_atom.ffcharge = mol2_atom.charge
                    tot_charge += mol2_atom.charge
                    lig_atoms.append(pdb_atom)
                except KeyError:
                    err = (
                        "Can't find HETATM {r.name} {r.res_seq} {a.name} "
                        "in MOL2 file").format(r=residue, a=pdb_atom)
                    _LOGGER.warning(err)
                    missing_atoms.append(pdb_atom)
    
        matched_atoms = hitlist + lig_atoms
    else:
        matched_atoms = hitlist
```
 Best regards

**Comment by sobolevnrm** [comment]
Thank you for trying out the untested part of the software that is not ready for public consumption or use.  😄 

We are working on making PDB2PQR more modular and are converting parts of the code to external dependencies.  That is the problem you experienced just now.  We've moved the PDBx dependency to https://github.com/Electrostatics/mmcif_pdbx and are in the process of pushing it to PyPI.  

In the meantime, I recommend using the code at https://github.com/Electrostatics/pdb2pqr/releases/tag/v2.1.1 as the last stable release.
