### ISSUE TITLE
Need regression tests for PEOE

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/pdb2pqr#7]
@intendo or @kozlac - would you be willing to develop some outputs for `PEOE` and `calcchi` as performing in PDB2PQR 2.1.1 https://github.com/Electrostatics/apbs-pdb2pqr/blob/433a1984a632b396bda11416b757d00e4ef5189e/pdb2pqr/pdb2pka/ligandclean/peoe_PDB2PQR.py ?  I'd like to develop some regression tests for the branch I'm working on.

Thank you!

**Comment by kozlac** [comment]
Do the following steps do what you are requesting:

- [ ] Checkout and set up to run PDB2PQR 2.1.1 with pdb2pka.

- [ ] Run 1HPX with LIG_1HPX.mol2 with different ph values.

- [ ] Capture the outputs of PEOE. Specifically the return atoms.

- [ ] Capture the output of calcchi for every atom.

Is this what you had in ming @sobolevnrm? If so, are there any other proteins you would like the output for?

**Comment by sobolevnrm** [comment]
Hi @kozlac.  Thanks for putting this together.  This list looks good but I think we only need to pick a specific titration state (save it as file that can be loaded in to reproduce) and then do what you described for calcchi, etc. for that specific titration state.

**Comment by kozlac** [comment]
@sobolevnrm  the file [1HPX_peoe_chi_output.txt](https://github.com/Electrostatics/pdb2pqr/files/4891302/1HPX_peoe_chi_output.txt) has the output from the peoe_PDB2PQR.py routines for 1HPX in the tests folder. The chi value is the chi value calculated during the last cycle. 

Would this file suffice? If so, should I push to a particular branch?
