### ISSUE TITLE
Clean up awkward PDB2PQR string formatting

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/pdb2pqr#80]
Where appropriate, replace old printf-style formatting with more modern formatting methods.

**Comment by intendo** [comment]
@sobolevnrm, if you point me to an example in the code with what it looks like now and how you want it to look, I can make updates on my own twime.

**Comment by sobolevnrm** [comment]
Much appreciated!  I'm trying to do to the strings in PDB2PQR what we did for PROPKA:  specifically replace old %-style string formatting with https://docs.python.org/3/library/stdtypes.html#str.format or https://docs.python.org/3/library/string.html#string.Template.  I think the switch will help remove a lot of redundant formatting code, especially in PDB/PQR output.

However, I think https://github.com/Electrostatics/apbs/issues/41 is a much better use of your time...
