### ISSUE TITLE
Add apbs-input support back into development branch

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/pdb2pqr#89]
in main.py, an exception is thrown if this input is an arg

**Comment by lqtza** [comment]
Commenting out  the line here https://github.com/Electrostatics/pdb2pqr/blob/29a8675596f6d6ba65a71eceb0e028689f733fba/pdb2pqr/main.py#L616 and then modifying the line below it to read `io.dump_apbs(args.output_pqr,args.apbs_input)` appears to restore apbs-input support for me.

**Comment by sobolevnrm** [comment]
Thank you; I've committed a change that fixes the issue in the way you suggested.  I checked the documentation for `dump_apbs` and I think it is correct.

**Comment by lqtza** [comment]
Awesome! Thanks!
